name: pokemon_details_view
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: ../../domain
  core:
    path: ../../core
  core_ui:
    path: ../../core_ui
  bloc_test: ^9.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: 5.5.0
  build_runner: ^2.4.11


flutter:
